### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by angelomelonas** [bunq/tinker_java#29]
Some improvements to be made:

- The documentation for the `go-pro` file is missing. See https://github.com/bunq/tinker_php/blob/develop/go-pro for comparison
- In the `CreatePsd2Configuration` file, there is a print out that is incorrect (`bunq-psd.conf` should be `bunq-psd2.conf`)
- In the `CreatePsd2Configuration` file, the Tinker header should be printed

There are likely more such easy improvements.

**Comment by angelomelonas** [comment]
@lexym wanna try some easy coding fixes? 😋

**Comment by lexym** [comment]
@angelomelonas exiting! assigned you some pull requests.

**Comment by angelomelonas** [comment]
@lexym closing this since you fixed all the issues 😄
