### ISSUE TITLE
Not clear which file to adjust to tinker.

### ISSUE THREAD

**Issue by patrickdw1991** [bunq/tinker_java#3]
The tinker script mentions that I have to adjust 'this file' to be able to see more but it's not clear what 'this file is'.
Also it's not clear how I can recompile the code.

**Comment by OGKevin** [comment]
@JordyHeemskerk could you please include the steps you took to compile the code. 

@patrickdw1991 I dont understand, you run the script `user-overview` and then it prints

https://github.com/bunq/tinker_java/blob/b03cbc2b84f35de9721a4083843c4015665d67f8/src/main/java/com/bunq/tinker/UserOverview.java#L46-L52

So what other file could it be ?

**Comment by OGKevin** [comment]
Ahh I see, the interface of java is a little different the the others. Normally one would do `tinker/user-overview.php` and then it makes sense that `this file` references to `tinker/user-overview` 🤔

**Comment by patrickdw1991** [comment]
@OGKevin It should reference to: `src/main/java/com/bunq/tinker/UserOverview.java`

**Comment by OGKevin** [comment]
@patrickdw1991 yes, but in the other tinker's, the user will just run `$ tinker/user-overview.php` and then the line `edit this file` will make sense and you just called the file :P but in java it doesn't cause the interface seems to be a little different 😁. So this is a copy pasta error.
